version: '3.8'

services:
  db:
    image: postgres:15
    container_name: multibus_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    container_name: multibus_api
    restart: always
    build: ./backend
    ports:
      - "3000:3000" 
    environment:
      DB_HOST: db 
      DB_PORT: ${DB_PORT}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_DATABASE: ${POSTGRES_DB}
    depends_on:
      - db

volumes:
  postgres_data: